name: Publish to Cloudflare

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@internxt'

      - name: Configure NPM
        run: |
          echo "registry=https://registry.yarnpkg.com/" > .npmrc
          echo "@internxt:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PERSONAL_ACCESS_TOKEN }}" >> .npmrc
          echo "always-auth=true" >> .npmrc
          npm config set legacy-peer-deps true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Configure environment
        run: |
          touch .env
          echo DRIVE_API_URL="https://drive.internxt.com/api" >> .env
          echo DRIVE_NEW_API_URL="https://api.internxt.com/drive" >> .env
          echo CRYPTO_SECRET="6KYQBP847D4ATSFA" >> .env
          echo MAGIC_IV="d139cb9a2cd17092e79e1861cf9d7023" >> .env
          echo MAGIC_SALT="38dce0391b49efba88dbc8c39ebf868f0267eb110bb0012ab27dc52a528d61b1d1ed9d76f400ff58e3240028442b1eab9bb84e111d9dadd997982dbde9dbd25e" >> .env
          echo JITSI_APP_ID="vpaas-magic-cookie-04a19c25aaab448c9cf74516ffb5ebf2" >> .env

      - name: Build application
        run: make compile deploy

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 157168a1684d7105399ec2339cf1281b
          projectName: meet-web
          directory: .